---
language: generic

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # Set from the repository settings:
    #- GH_TOKEN=[secure]
    #- NETLIFY_AUTH_TOKEN=[secure]

git:
  depth: false

install:
  - node --version
  - nvm use 11
  - node --version
  - source ./.ci/travis-fix-env

script:
  - ./.ci/pr-build-website-preview
  - ./.ci/publish-website-preview
  - ./.ci/blc-website-preview

deploy:
  - provider: script
    script: ./.ci/publish-website
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./.ci/publish-website
    skip_cleanup: true
    on:
      branch: early-access
