{
 "title": "Ambassador",
 "description": "Ambassador dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(ambassador_diagnostics_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(ambassador_diagnostics_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Ambassador - Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "ambassador_diagnostics_info{namespace=~\"$namespace\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Last control plane operation time ($pod)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 1 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "ambassador_reconfiguration_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Reconfiguration"
    },
    {
     "expr": "ambassador_fetcher_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Fetcher"
    },
    {
     "expr": "ambassador_aconf_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "AConf"
    },
    {
     "expr": "ambassador_ir_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "IR"
    },
    {
     "expr": "ambassador_econf_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "EConf"
    },
    {
     "expr": "ambassador_diagnostics_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Diagnostics"
    }
   ]
  },
  {
   "title": "Ambassador",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "amb-sidecar memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " ambassador_edge_stack_go_memstats_alloc_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Ambassador - Envoy Data Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ambassador Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "API Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http1_active[1m]))",
     "legendFormat": "HTTP/1"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http2_active_active[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_upgrades_active[1m]))",
     "legendFormat": "Websocket"
    }
   ]
  },
  {
   "title": "Registered Services",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(envoy_cluster_manager_active_clusters)"
    }
   ]
  }
 ]
}